-- 실습 테이블 생성
CREATE TABLE TBL_STUDENT
(
    SID  NUMBER
,   NAME    VARCHAR(30)
,   TEL VARCHAR(40)
,   CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)

);
--==>> Table TBL_STUDENT이(가) 생성되었습니다.
CREATE SEQUENCE STUDENTLISTSEQ
NOCACHE;

COMMIT;

-- 샘플 데이터 입력
INSERT INTO TBL_STUDENT(SID,NAME, TEL) VALUES(STUDENTLISTSEQ.NEXTVAL,'홍길동','010-8888-8888');
INSERT INTO TBL_STUDENT(SID,NAME, TEL) VALUES(STUDENTLISTSEQ.NEXTVAL,'김선아','010-2222-1111');
INSERT INTO TBL_STUDENT(SID,NAME, TEL) VALUES(STUDENTLISTSEQ.NEXTVAL,'김성희','010-3333-1111');
INSERT INTO TBL_STUDENT(SID,NAME, TEL) VALUES(STUDENTLISTSEQ.NEXTVAL,'김정규','010-4444-1111');
--==>> 1 행 이(가) 삽입되었습니다. * 4

COMMIT;
CREATE TABLE TBL_GRADE
(
    SID  NUMBER
,   SUB1 NUMBER(3)
,   SUB2 NUMBER(3)
,   SUB3 NUMBER(3)
,   CONSTRAINT GRADE_SID_PK PRIMARY KEY(SID)
,   CONSTRAINT GRADE_SID_FK FOREIGN KEY(SID) REFERENCES TBL_STUDENT(SID)
,   CONSTRAINT GRADE_SUB1_CK CHECK(SUB1 BETWEEN 0 AND 100)
,   CONSTRAINT GRADE_SUB2_CK CHECK(SUB2 BETWEEN 0 AND 100)
,   CONSTRAINT GRADE_SUB3_CK CHECK(SUB3 BETWEEN 0 AND 100)
);
--==>> Table TBL_GRADE이(가) 생성되었습니다.


INSERT INTO TBL_GRADE(SID,SUB1, SUB2,SUB3) VALUES(1,60,80,20);
INSERT INTO TBL_GRADE(SID,SUB1, SUB2,SUB3) VALUES(2,70,60,50);
INSERT INTO TBL_GRADE(SID,SUB1, SUB2,SUB3) VALUES(3,50,40,30);
INSERT INTO TBL_GRADE(SID,SUB1, SUB2,SUB3) VALUES(4,90,90,20);
--==>> 1 행 이(가) 삽입되었습니다. * 4

SELECT * FROM TBL_GRADE;

COMMIT;

-- STUDENT VIEW
CREATE OR REPLACE VIEW STUDENTVIEW
AS
SELECT S.SID,S.NAME,S.TEL,
(SELECT COUNT(*) FROM TBL_GRADE WHERE SID=S.SID ) AS SUB
FROM TBL_STUDENT S ;
--==>> View STUDENTVIEW이(가) 생성되었습니다.


SELECT * FROM STUDENTVIEW;

-- GRADEVIEW
CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT S.SID,S.NAME,G.SUB1,G.SUB2,G.SUB3,NVL2((G.SUB1+G.SUB2+G.SUB3), (G.SUB1+G.SUB2+G.SUB3), NULL) AS TOT
,TRUNC(NVL2((G.SUB1+G.SUB2+G.SUB3)/3.0, (G.SUB1+G.SUB2+G.SUB3)/3.0, NULL),2) AS AVG
, CASE WHEN  (G.SUB1<40) OR (G.SUB2<40) OR (G.SUB3<40) THEN '과락'
WHEN  TRUNC(NVL2((G.SUB1+G.SUB2+G.SUB3)/3.0, (G.SUB1+G.SUB2+G.SUB3)/3.0, 0),2)<60 THEN '불합격'
ELSE '합격'
END AS CH
FROM  TBL_STUDENT S LEFT JOIN TBL_GRADE G
ON S.SID=G.SID;
--==>> View GRADEVIEW이(가) 생성되었습니다.


SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
		FROM GRADEVIEW
		ORDER BY SID;
SELECT * FROM GRADEVIEW;

SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
FROM GRADEVIEW
ORDER BY SID;
commit;
SELECT SID, NAME, TEL
FROM TBL_STUDENT
ORDER BY SID;

SELECT COUNT(*) AS COUNT
FROM TBL_STUDENT;

SELECT NAME, TEL
FROM TBL_STUDENT
WHERE SID = 1;

UPDATE TBL_STUDENT
SET NAME = '홍길동'
  , TEL = '010-5555-5555'
WHERE SID = 1;

DROP VIEW GRADEVIEW;

ROLLBACK;